---
title       : "Analyzing MPG Performance vs Automobile Design"
subtitle    : Developing Data Products Project Part 2
author      : "paperless247"
job         : Reproducible Pitch Presentation
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Dataset

`mtcars` dataset is used to analyze automobile performance and create ShinyApp (for Part 1)

### Motor Trend mtcars Dataset

> The mtcars data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance.

```{r}
library(datasets)
head(mtcars, 5)
```

--- .class #id 

## Dataset Description

**Dataset has 32 observations on 11 variables**

| Index | Variable | Description |
------- | ----- | ------ |
| 1 | mpg | Miles/(US) gallon |
| 2  | cyl | Number of cylinders |
| 3  | disp | Displacement (cu.in.) |
| 4  | hp | Gross horsepower |
| 5	| drat | Rear axle ratio |
| 6	| wt | Weight (lb/1000) |
| 7	| qsec | 1/4 mile time |
| 8	| vs | V/S |
| 9	| am | Transmission (0 = automatic, 1 = manual) |
| 10	| gear | Number of forward gears |
| 11	| carb | Number of carburetors |

--- .class #id 

## Analysis

Then main script:

```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=mpgData)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(mpgData, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })
```

---

## Shiny Application and Github Repository

### Shiny Application

URL: *https://etran.shinyapps.io/test/*

### Github Repository

URL: *https://github.com/paperless247/DS9_Proj_1*

Thank you for reading and grading!
